# Generated by Django 5.1.7 on 2025-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='transcoding_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcoding_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='transcoding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
