# Generated by Django 5.1.7 on 2025-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_processed_video_video_transcoding_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transcoding_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
