# Generated by Django 5.1.7 on 2025-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_transcoding_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcoding_task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
